CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    display_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS orders (
    order_id BIGINT PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    street VARCHAR(255),
    city VARCHAR(128),
    state VARCHAR(32),
    postal_code VARCHAR(16),
    country VARCHAR(8)
);

CREATE TABLE IF NOT EXISTS order_line_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    sku VARCHAR(32) NOT NULL,
    product_name VARCHAR(255) NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL
);

CREATE TABLE IF NOT EXISTS inventory (
    sku VARCHAR(32) PRIMARY KEY,
    quantity INT NOT NULL
);

CREATE TABLE IF NOT EXISTS products (
    sku VARCHAR(32) PRIMARY KEY,
    product_name VARCHAR(255) NOT NULL,
    unit_price DECIMAL(12, 2) NOT NULL,
    category VARCHAR(64) NOT NULL,
    express_eligible BOOLEAN NOT NULL
);
